/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : AlertId,
  'patient' : PatientId,
  'alertType' : { 'emergency' : null } |
    { 'medication' : null } |
    { 'vitals' : null },
  'message' : string,
  'timestamp' : Time,
}
export type AlertId = bigint;
export interface Appointment {
  'id' : AppointmentId,
  'doctor' : DoctorId,
  'dateTime' : Time,
  'reason' : string,
}
export type AppointmentId = bigint;
export type DoctorId = Principal;
export interface DoctorProfile { 'name' : string, 'specialty' : string }
export interface HomeNurseRequest {
  'id' : HomeNurseRequestId,
  'patient' : PatientId,
  'details' : string,
  'dateTime' : Time,
}
export type HomeNurseRequestId = bigint;
export type MedicationId = bigint;
export interface MedicationReminder {
  'id' : MedicationId,
  'dosage' : string,
  'name' : string,
  'nextDue' : Time,
  'frequency' : string,
}
export type PatientId = Principal;
export interface PatientProfile {
  'age' : bigint,
  'name' : string,
  'connectedDevices' : Array<string>,
  'medicalHistory' : string,
  'primaryDoctor' : [] | [DoctorId],
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : UserRole }
export type UserRole = { 'patient' : null } |
  { 'doctor' : null } |
  { 'familyMember' : PatientId };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VitalsReading {
  'temperature' : number,
  'bloodPressure' : string,
  'heartRate' : bigint,
  'timestamp' : Time,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAppointment' : ActorMethod<[Appointment], undefined>,
  'addHomeNurseRequest' : ActorMethod<[HomeNurseRequest], undefined>,
  'addMedicationReminder' : ActorMethod<[MedicationReminder], undefined>,
  'addVitalsReading' : ActorMethod<[VitalsReading], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'deleteAppointment' : ActorMethod<[PatientId, AppointmentId], undefined>,
  'deleteMedicationReminder' : ActorMethod<
    [PatientId, MedicationId],
    undefined
  >,
  'getAlerts' : ActorMethod<[PatientId], Array<Alert>>,
  'getAllPatients' : ActorMethod<[], Array<[PatientId, PatientProfile]>>,
  'getAppointments' : ActorMethod<[PatientId], Array<Appointment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getDoctorProfile' : ActorMethod<[DoctorId], [] | [DoctorProfile]>,
  'getFamilyAccess' : ActorMethod<[PatientId], Array<Principal>>,
  'getHomeNurseRequests' : ActorMethod<[PatientId], Array<HomeNurseRequest>>,
  'getMedicationReminders' : ActorMethod<
    [PatientId],
    Array<MedicationReminder>
  >,
  'getMyPatients' : ActorMethod<[], Array<[PatientId, PatientProfile]>>,
  'getMyPatientsAlerts' : ActorMethod<[], Array<Alert>>,
  'getPatientProfile' : ActorMethod<[PatientId], [] | [PatientProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVitalsReadings' : ActorMethod<[PatientId], Array<VitalsReading>>,
  'grantFamilyAccess' : ActorMethod<[Principal], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'revokeFamilyAccess' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDoctorProfile' : ActorMethod<[DoctorProfile], undefined>,
  'savePatientProfile' : ActorMethod<[PatientProfile], undefined>,
  'sendEmergencyAlert' : ActorMethod<[string], undefined>,
  'updateAppointment' : ActorMethod<
    [PatientId, AppointmentId, Appointment],
    undefined
  >,
  'updateMedicationReminder' : ActorMethod<
    [PatientId, MedicationId, MedicationReminder],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];