/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AppointmentId = IDL.Nat;
export const DoctorId = IDL.Principal;
export const Time = IDL.Int;
export const Appointment = IDL.Record({
  'id' : AppointmentId,
  'doctor' : DoctorId,
  'dateTime' : Time,
  'reason' : IDL.Text,
});
export const HomeNurseRequestId = IDL.Nat;
export const PatientId = IDL.Principal;
export const HomeNurseRequest = IDL.Record({
  'id' : HomeNurseRequestId,
  'patient' : PatientId,
  'details' : IDL.Text,
  'dateTime' : Time,
});
export const MedicationId = IDL.Nat;
export const MedicationReminder = IDL.Record({
  'id' : MedicationId,
  'dosage' : IDL.Text,
  'name' : IDL.Text,
  'nextDue' : Time,
  'frequency' : IDL.Text,
});
export const VitalsReading = IDL.Record({
  'temperature' : IDL.Float64,
  'bloodPressure' : IDL.Text,
  'heartRate' : IDL.Nat,
  'timestamp' : Time,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AlertId = IDL.Nat;
export const Alert = IDL.Record({
  'id' : AlertId,
  'patient' : PatientId,
  'alertType' : IDL.Variant({
    'emergency' : IDL.Null,
    'medication' : IDL.Null,
    'vitals' : IDL.Null,
  }),
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const PatientProfile = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'connectedDevices' : IDL.Vec(IDL.Text),
  'medicalHistory' : IDL.Text,
  'primaryDoctor' : IDL.Opt(DoctorId),
});
export const UserRole = IDL.Variant({
  'patient' : IDL.Null,
  'doctor' : IDL.Null,
  'familyMember' : PatientId,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
export const DoctorProfile = IDL.Record({
  'name' : IDL.Text,
  'specialty' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAppointment' : IDL.Func([Appointment], [], []),
  'addHomeNurseRequest' : IDL.Func([HomeNurseRequest], [], []),
  'addMedicationReminder' : IDL.Func([MedicationReminder], [], []),
  'addVitalsReading' : IDL.Func([VitalsReading], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'deleteAppointment' : IDL.Func([PatientId, AppointmentId], [], []),
  'deleteMedicationReminder' : IDL.Func([PatientId, MedicationId], [], []),
  'getAlerts' : IDL.Func([PatientId], [IDL.Vec(Alert)], ['query']),
  'getAllPatients' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(PatientId, PatientProfile))],
      ['query'],
    ),
  'getAppointments' : IDL.Func([PatientId], [IDL.Vec(Appointment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getDoctorProfile' : IDL.Func(
      [DoctorId],
      [IDL.Opt(DoctorProfile)],
      ['query'],
    ),
  'getFamilyAccess' : IDL.Func(
      [PatientId],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getHomeNurseRequests' : IDL.Func(
      [PatientId],
      [IDL.Vec(HomeNurseRequest)],
      ['query'],
    ),
  'getMedicationReminders' : IDL.Func(
      [PatientId],
      [IDL.Vec(MedicationReminder)],
      ['query'],
    ),
  'getMyPatients' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(PatientId, PatientProfile))],
      ['query'],
    ),
  'getMyPatientsAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getPatientProfile' : IDL.Func(
      [PatientId],
      [IDL.Opt(PatientProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVitalsReadings' : IDL.Func(
      [PatientId],
      [IDL.Vec(VitalsReading)],
      ['query'],
    ),
  'grantFamilyAccess' : IDL.Func([IDL.Principal], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'revokeFamilyAccess' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDoctorProfile' : IDL.Func([DoctorProfile], [], []),
  'savePatientProfile' : IDL.Func([PatientProfile], [], []),
  'sendEmergencyAlert' : IDL.Func([IDL.Text], [], []),
  'updateAppointment' : IDL.Func(
      [PatientId, AppointmentId, Appointment],
      [],
      [],
    ),
  'updateMedicationReminder' : IDL.Func(
      [PatientId, MedicationId, MedicationReminder],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AppointmentId = IDL.Nat;
  const DoctorId = IDL.Principal;
  const Time = IDL.Int;
  const Appointment = IDL.Record({
    'id' : AppointmentId,
    'doctor' : DoctorId,
    'dateTime' : Time,
    'reason' : IDL.Text,
  });
  const HomeNurseRequestId = IDL.Nat;
  const PatientId = IDL.Principal;
  const HomeNurseRequest = IDL.Record({
    'id' : HomeNurseRequestId,
    'patient' : PatientId,
    'details' : IDL.Text,
    'dateTime' : Time,
  });
  const MedicationId = IDL.Nat;
  const MedicationReminder = IDL.Record({
    'id' : MedicationId,
    'dosage' : IDL.Text,
    'name' : IDL.Text,
    'nextDue' : Time,
    'frequency' : IDL.Text,
  });
  const VitalsReading = IDL.Record({
    'temperature' : IDL.Float64,
    'bloodPressure' : IDL.Text,
    'heartRate' : IDL.Nat,
    'timestamp' : Time,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AlertId = IDL.Nat;
  const Alert = IDL.Record({
    'id' : AlertId,
    'patient' : PatientId,
    'alertType' : IDL.Variant({
      'emergency' : IDL.Null,
      'medication' : IDL.Null,
      'vitals' : IDL.Null,
    }),
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const PatientProfile = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'connectedDevices' : IDL.Vec(IDL.Text),
    'medicalHistory' : IDL.Text,
    'primaryDoctor' : IDL.Opt(DoctorId),
  });
  const UserRole = IDL.Variant({
    'patient' : IDL.Null,
    'doctor' : IDL.Null,
    'familyMember' : PatientId,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
  const DoctorProfile = IDL.Record({
    'name' : IDL.Text,
    'specialty' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAppointment' : IDL.Func([Appointment], [], []),
    'addHomeNurseRequest' : IDL.Func([HomeNurseRequest], [], []),
    'addMedicationReminder' : IDL.Func([MedicationReminder], [], []),
    'addVitalsReading' : IDL.Func([VitalsReading], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'deleteAppointment' : IDL.Func([PatientId, AppointmentId], [], []),
    'deleteMedicationReminder' : IDL.Func([PatientId, MedicationId], [], []),
    'getAlerts' : IDL.Func([PatientId], [IDL.Vec(Alert)], ['query']),
    'getAllPatients' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(PatientId, PatientProfile))],
        ['query'],
      ),
    'getAppointments' : IDL.Func(
        [PatientId],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getDoctorProfile' : IDL.Func(
        [DoctorId],
        [IDL.Opt(DoctorProfile)],
        ['query'],
      ),
    'getFamilyAccess' : IDL.Func(
        [PatientId],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getHomeNurseRequests' : IDL.Func(
        [PatientId],
        [IDL.Vec(HomeNurseRequest)],
        ['query'],
      ),
    'getMedicationReminders' : IDL.Func(
        [PatientId],
        [IDL.Vec(MedicationReminder)],
        ['query'],
      ),
    'getMyPatients' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(PatientId, PatientProfile))],
        ['query'],
      ),
    'getMyPatientsAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getPatientProfile' : IDL.Func(
        [PatientId],
        [IDL.Opt(PatientProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVitalsReadings' : IDL.Func(
        [PatientId],
        [IDL.Vec(VitalsReading)],
        ['query'],
      ),
    'grantFamilyAccess' : IDL.Func([IDL.Principal], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'revokeFamilyAccess' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDoctorProfile' : IDL.Func([DoctorProfile], [], []),
    'savePatientProfile' : IDL.Func([PatientProfile], [], []),
    'sendEmergencyAlert' : IDL.Func([IDL.Text], [], []),
    'updateAppointment' : IDL.Func(
        [PatientId, AppointmentId, Appointment],
        [],
        [],
      ),
    'updateMedicationReminder' : IDL.Func(
        [PatientId, MedicationId, MedicationReminder],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };