/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type HomeNurseRequestId = bigint;
export type Time = bigint;
export interface VitalsReading {
    temperature: number;
    bloodPressure: string;
    heartRate: bigint;
    timestamp: Time;
}
export type MedicationId = bigint;
export interface DoctorProfile {
    name: string;
    specialty: string;
}
export type UserRole = {
    __kind__: "patient";
    patient: null;
} | {
    __kind__: "doctor";
    doctor: null;
} | {
    __kind__: "familyMember";
    familyMember: PatientId;
};
export interface MedicationReminder {
    id: MedicationId;
    dosage: string;
    name: string;
    nextDue: Time;
    frequency: string;
}
export type DoctorId = Principal;
export type AppointmentId = bigint;
export type PatientId = Principal;
export type AlertId = bigint;
export interface HomeNurseRequest {
    id: HomeNurseRequestId;
    patient: PatientId;
    details: string;
    dateTime: Time;
}
export interface PatientProfile {
    age: bigint;
    name: string;
    connectedDevices: Array<string>;
    medicalHistory: string;
    primaryDoctor?: DoctorId;
}
export interface Appointment {
    id: AppointmentId;
    doctor: DoctorId;
    dateTime: Time;
    reason: string;
}
export interface Alert {
    id: AlertId;
    patient: PatientId;
    alertType: Variant_emergency_medication_vitals;
    message: string;
    timestamp: Time;
}
export interface UserProfile {
    name: string;
    role: UserRole;
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_emergency_medication_vitals {
    emergency = "emergency",
    medication = "medication",
    vitals = "vitals"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAppointment(appointment: Appointment): Promise<void>;
    addHomeNurseRequest(request: HomeNurseRequest): Promise<void>;
    addMedicationReminder(reminder: MedicationReminder): Promise<void>;
    addVitalsReading(reading: VitalsReading): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    deleteAppointment(patient: PatientId, appointmentId: AppointmentId): Promise<void>;
    deleteMedicationReminder(patient: PatientId, medicationId: MedicationId): Promise<void>;
    getAlerts(patient: PatientId): Promise<Array<Alert>>;
    getAllPatients(): Promise<Array<[PatientId, PatientProfile]>>;
    getAppointments(patient: PatientId): Promise<Array<Appointment>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getDoctorProfile(doctor: DoctorId): Promise<DoctorProfile | null>;
    getFamilyAccess(patient: PatientId): Promise<Array<Principal>>;
    getHomeNurseRequests(patient: PatientId): Promise<Array<HomeNurseRequest>>;
    getMedicationReminders(patient: PatientId): Promise<Array<MedicationReminder>>;
    getMyPatients(): Promise<Array<[PatientId, PatientProfile]>>;
    getMyPatientsAlerts(): Promise<Array<Alert>>;
    getPatientProfile(patient: PatientId): Promise<PatientProfile | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVitalsReadings(patient: PatientId): Promise<Array<VitalsReading>>;
    grantFamilyAccess(familyMemberId: Principal): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    revokeFamilyAccess(familyMemberId: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveDoctorProfile(profile: DoctorProfile): Promise<void>;
    savePatientProfile(profile: PatientProfile): Promise<void>;
    sendEmergencyAlert(message: string): Promise<void>;
    updateAppointment(patient: PatientId, appointmentId: AppointmentId, appointment: Appointment): Promise<void>;
    updateMedicationReminder(patient: PatientId, medicationId: MedicationId, reminder: MedicationReminder): Promise<void>;
}
import type { Alert as _Alert, AlertId as _AlertId, DoctorId as _DoctorId, DoctorProfile as _DoctorProfile, PatientId as _PatientId, PatientProfile as _PatientProfile, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAppointment(arg0: Appointment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAppointment(arg0);
            return result;
        }
    }
    async addHomeNurseRequest(arg0: HomeNurseRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHomeNurseRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHomeNurseRequest(arg0);
            return result;
        }
    }
    async addMedicationReminder(arg0: MedicationReminder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedicationReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedicationReminder(arg0);
            return result;
        }
    }
    async addVitalsReading(arg0: VitalsReading): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVitalsReading(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVitalsReading(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAppointment(arg0: PatientId, arg1: AppointmentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAppointment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAppointment(arg0, arg1);
            return result;
        }
    }
    async deleteMedicationReminder(arg0: PatientId, arg1: MedicationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedicationReminder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedicationReminder(arg0, arg1);
            return result;
        }
    }
    async getAlerts(arg0: PatientId): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlerts(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlerts(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPatients(): Promise<Array<[PatientId, PatientProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatients();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatients();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppointments(arg0: PatientId): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointments(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoctorProfile(arg0: DoctorId): Promise<DoctorProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctorProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctorProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFamilyAccess(arg0: PatientId): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFamilyAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFamilyAccess(arg0);
            return result;
        }
    }
    async getHomeNurseRequests(arg0: PatientId): Promise<Array<HomeNurseRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomeNurseRequests(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomeNurseRequests(arg0);
            return result;
        }
    }
    async getMedicationReminders(arg0: PatientId): Promise<Array<MedicationReminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicationReminders(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicationReminders(arg0);
            return result;
        }
    }
    async getMyPatients(): Promise<Array<[PatientId, PatientProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPatients();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPatients();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPatientsAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPatientsAlerts();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPatientsAlerts();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatientProfile(arg0: PatientId): Promise<PatientProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVitalsReadings(arg0: PatientId): Promise<Array<VitalsReading>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVitalsReadings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVitalsReadings(arg0);
            return result;
        }
    }
    async grantFamilyAccess(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.grantFamilyAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantFamilyAccess(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async revokeFamilyAccess(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeFamilyAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeFamilyAccess(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveDoctorProfile(arg0: DoctorProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDoctorProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDoctorProfile(arg0);
            return result;
        }
    }
    async savePatientProfile(arg0: PatientProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePatientProfile(to_candid_PatientProfile_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePatientProfile(to_candid_PatientProfile_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendEmergencyAlert(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendEmergencyAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendEmergencyAlert(arg0);
            return result;
        }
    }
    async updateAppointment(arg0: PatientId, arg1: AppointmentId, arg2: Appointment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointment(arg0, arg1, arg2);
            return result;
        }
    }
    async updateMedicationReminder(arg0: PatientId, arg1: MedicationId, arg2: MedicationReminder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedicationReminder(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedicationReminder(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_Alert_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alert): Alert {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_PatientProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PatientProfile): PatientProfile {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DoctorId]): DoctorId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DoctorProfile]): DoctorProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PatientProfile]): PatientProfile | null {
    return value.length === 0 ? null : from_candid_PatientProfile_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    name: string;
    connectedDevices: Array<string>;
    medicalHistory: string;
    primaryDoctor: [] | [_DoctorId];
}): {
    age: bigint;
    name: string;
    connectedDevices: Array<string>;
    medicalHistory: string;
    primaryDoctor?: DoctorId;
} {
    return {
        age: value.age,
        name: value.name,
        connectedDevices: value.connectedDevices,
        medicalHistory: value.medicalHistory,
        primaryDoctor: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.primaryDoctor))
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _UserRole;
}): {
    name: string;
    role: UserRole;
} {
    return {
        name: value.name,
        role: from_candid_UserRole_n15(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AlertId;
    patient: _PatientId;
    alertType: {
        emergency: null;
    } | {
        medication: null;
    } | {
        vitals: null;
    };
    message: string;
    timestamp: _Time;
}): {
    id: AlertId;
    patient: PatientId;
    alertType: Variant_emergency_medication_vitals;
    message: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        patient: value.patient,
        alertType: from_candid_variant_n6(_uploadFile, _downloadFile, value.alertType),
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_tuple_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_PatientId, _PatientProfile]): [PatientId, PatientProfile] {
    return [
        value[0],
        from_candid_PatientProfile_n9(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patient: null;
} | {
    doctor: null;
} | {
    familyMember: _PatientId;
}): {
    __kind__: "patient";
    patient: null;
} | {
    __kind__: "doctor";
    doctor: null;
} | {
    __kind__: "familyMember";
    familyMember: PatientId;
} {
    return "patient" in value ? {
        __kind__: "patient",
        patient: value.patient
    } : "doctor" in value ? {
        __kind__: "doctor",
        doctor: value.doctor
    } : "familyMember" in value ? {
        __kind__: "familyMember",
        familyMember: value.familyMember
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    emergency: null;
} | {
    medication: null;
} | {
    vitals: null;
}): Variant_emergency_medication_vitals {
    return "emergency" in value ? Variant_emergency_medication_vitals.emergency : "medication" in value ? Variant_emergency_medication_vitals.medication : "vitals" in value ? Variant_emergency_medication_vitals.vitals : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Alert>): Array<Alert> {
    return value.map((x)=>from_candid_Alert_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_PatientId, _PatientProfile]>): Array<[PatientId, PatientProfile]> {
    return value.map((x)=>from_candid_tuple_n8(_uploadFile, _downloadFile, x));
}
function to_candid_PatientProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PatientProfile): _PatientProfile {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: UserRole;
}): {
    name: string;
    role: _UserRole;
} {
    return {
        name: value.name,
        role: to_candid_UserRole_n23(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    name: string;
    connectedDevices: Array<string>;
    medicalHistory: string;
    primaryDoctor?: DoctorId;
}): {
    age: bigint;
    name: string;
    connectedDevices: Array<string>;
    medicalHistory: string;
    primaryDoctor: [] | [_DoctorId];
} {
    return {
        age: value.age,
        name: value.name,
        connectedDevices: value.connectedDevices,
        medicalHistory: value.medicalHistory,
        primaryDoctor: value.primaryDoctor ? candid_some(value.primaryDoctor) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "patient";
    patient: null;
} | {
    __kind__: "doctor";
    doctor: null;
} | {
    __kind__: "familyMember";
    familyMember: PatientId;
}): {
    patient: null;
} | {
    doctor: null;
} | {
    familyMember: _PatientId;
} {
    return value.__kind__ === "patient" ? {
        patient: value.patient
    } : value.__kind__ === "doctor" ? {
        doctor: value.doctor
    } : value.__kind__ === "familyMember" ? {
        familyMember: value.familyMember
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
